name: ZAP Baseline Scan
on: workflow_dispatch
permissions:
  issues: write
  contents: read
jobs:
  zap:
    runs-on: ubuntu-latest
    name: ZAP Baseline Scan
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.15.0
        with:
          target: 'https://ginandjuice.shop'
